### ISSUE TITLE
HTTP proxying doesn't work

### ISSUE THREAD

**Issue by sorenstoutner** [guardianproject/orbot#185] opened 2018-12-28 05:07 UTC
This is only a problem with HTTP proxying, HTTPS proxying still works.  This was a regression introduced in 16.0.2-RC-1 relating to the change from using Privoxy to the built-in HTTP proxying.

It was originally reported at https://trac.torproject.org/projects/tor/ticket/26764, which has further details.

**Comment by pgerber** [comment] 2019-06-04 17:35
This appears to be a duplicate of #159.

**Comment by sorenstoutner** [comment] 2019-12-22 02:37
With the upcoming 3.3 release of Privacy Browser, I have switched the code to use the new AndroidX ProxyController, which allows Android's WebViews to use SOCKS proxies.

​https://developer.android.com/reference/androidx/webkit/ProxyConfig.Builder.html#addProxyRule(java.lang.String)

As such, this is not longer an issue for my app. But it may still be a problem for some other people.

**Closed** 2020-11-24 14:46 UTC
