### ISSUE TITLE
Constant 100% CPU usage

### ISSUE THREAD

**Issue by SkewedZeppelin** [guardianproject/orbot#627] opened 2022-03-07 02:14 UTC
I installed [Orbot for Android 16.6.0 RC 3](https://github.com/guardianproject/orbot/releases/tag/16.6.0-RC-3-tor.0.4.6.9) last night.
A few hours back I noticed my phone very warm.
Just a few minutes ago it completely died.
Plugged it in and rebooted, checked it 20mins later to see it was barely charging, and checked top via adb shell to see Orbot using 100% of a core.

I cannot reproduce this issue on [Orbot for Android 16.6.0 RC 2](https://github.com/guardianproject/orbot/releases/tag/16.6.0-RC-2-tor.0.4.6.9).

Last time I saw this was a long while ago https://github.com/guardianproject/orbot/issues/208#issuecomment-623570253

Looking at the battery graph in system settings shows a plateau and then a large down ramp, the switch was around the time I switched from wifi to cellular (and eventually back). Maybe it got stuck in a loop somewhere with the new connectivity state change listener?

Phone is Essential Phone with DivestOS 18.1/11.0

**Comment by bitmold** [comment] 2022-03-07 03:25
Looking into this now...

`top` reports extremely high CPU usage when the VPN Service is running, but not if it's disabled... Obviously to some extent the VPN should increase CPU usage but not to this extent. The reason has something to do with that.....

**Comment by bitmold** [comment] 2022-03-07 03:27
> Maybe it got stuck in a loop somewhere with the new connectivity state change listener?

This doesn't seem to be happening as far as I can tell

**Comment by bitmold** [comment] 2022-03-07 03:44
One issue it seems is that even after stopping the VPN you'll continue to get messages like this: 

> 2022-03-06 23:40:40.703 6474-9735/org.torproject.android E/bim: error writing to VPN fd
    java.io.IOException: write failed: EBADF (Bad file descriptor)
        at libcore.io.IoBridge.write(IoBridge.java:540)
        at java.io.FileOutputStream.write(FileOutputStream.java:398)
        at java.io.DataOutputStream.write(DataOutputStream.java:107)
        at java.io.FilterOutputStream.write(FilterOutputStream.java:103)
        at org.torproject.android.service.vpn.OrbotVpnManager.lambda$startListeningToFD$1(OrbotVpnManager.java:308)
        at org.torproject.android.service.vpn.OrbotVpnManager$$ExternalSyntheticLambda0.writePacket(Unknown Source:2)
     Caused by: android.system.ErrnoException: write failed: EBADF (Bad file descriptor)
        at libcore.io.Linux.writeBytes(Native Method)
        at libcore.io.Linux.write(Linux.java:293)
        at libcore.io.ForwardingOs.write(ForwardingOs.java:240)
        at libcore.io.BlockGuardOs.write(BlockGuardOs.java:418)
        at libcore.io.ForwardingOs.write(ForwardingOs.java:240)
        at libcore.io.IoBridge.write(IoBridge.java:535)
        at java.io.FileOutputStream.write(FileOutputStream.java:398) 
        at java.io.DataOutputStream.write(DataOutputStream.java:107) 
        at java.io.FilterOutputStream.write(FilterOutputStream.java:103) 
        at org.torproject.android.service.vpn.OrbotVpnManager.lambda$startListeningToFD$1(OrbotVpnManager.java:308) 
        at org.torproject.android.service.vpn.OrbotVpnManager$$ExternalSyntheticLambda0.writePacket(Unknown Source:2)

**Comment by bitmold** [comment] 2022-03-07 18:45
This should be fixed on devices Lollipop+ and we will have an RC4 out soon, thank you for finding this!

**Closed** 2022-03-07 18:44 UTC

**Comment by SkewedZeppelin** [comment] 2022-03-08 02:57
Thanks!

**Comment by n8fr8** [comment] 2022-03-08 03:12
https://github.com/guardianproject/orbot/releases/tag/16.6.0-RC-4-tor.0.4.6.9
