### ISSUE TITLE
Add: orbot quick start/stop & exit button

### ISSUE THREAD

**Issue by anwar-alsilwy** [guardianproject/orbot#703] opened 2022-06-23 04:53 UTC
Hi
First of all, thank you for your hard work.
I believe it will be great to add orbot quick Start/Stop & Exit button to the Android quick panel, without needing to open the whole UI of application,
 just like Adguard,1DM,Shazam apps .... etc
See picture below:
![Screenshot_20220622-075609_One UI Home](https://user-images.githubusercontent.com/71539261/175211420-60ba3f14-7150-49c5-893a-588159242195.jpg)

**Comment by bitmold** [comment] 2022-07-27 16:56
Closing because duplicate of #181

**Closed** 2022-07-27 16:56 UTC
