### ISSUE TITLE
Can't deselect some apps in Apps VPN Mode menu

### ISSUE THREAD

**Issue by bungabunga** [guardianproject/orbot#101] opened 2017-11-22 22:12 UTC
There are some (system) apps selected in the Apps VPN Mode menu that i didn't select and can not be deselected. If i deselect them, they are selected again when i return to that menu.

Apps:
APN Updater
Retail Demo
SIM Detection
Screen
STAMINA mode
Settings
Service Menu
USB
devicemonitor
com.sonyericsson....(something)

My device: Sony Xperia XZ
OS: Android 7.1.1.
Orbot version: 15.5.1-RC-2-multi-SDK23

**Comment by bitmold** [comment] 2020-11-29 20:30
Closing this because I can't reproduce it and there have been many changes to the VPN selection screen over the past 3 years.

If you're still here @bungabunga could you please check to see if this issue still exists with our latest release https://github.com/guardianproject/orbot/releases/tag/16.3.3-RC-1-tor-0.4.3.6

**Closed by bitmold** 2020-11-29 20:30 UTC
