### ISSUE TITLE
Orbot won't load past 5%

### ISSUE THREAD

**Issue by raelschiffler** [guardianproject/orbot#533] opened 2021-10-18 12:35 UTC
![Screenshot_20211018-092323](https://user-images.githubusercontent.com/16996501/137730461-6e7ac15f-c35b-4593-8619-74cd9e29fba7.png)
![Screenshot_20211018-092135](https://user-images.githubusercontent.com/16996501/137730468-e0c6826d-5a41-4324-9c7c-9391427398df.png)
![Screenshot_20211018-092950](https://user-images.githubusercontent.com/16996501/137730611-cbc24cd8-221e-4e4e-baae-6d511dee5c9c.png)

First time I ran orbot in my new device (Blackview BV9900Pro Serial number BV9900ProQEEA33256) it connected smoothly. After a few device restarts it doesn't load past 5% and never past 2% in bridge mode.
This version I screenshoted I download the APK directly from this GitHub project. I also tried after these errors the Google play store version and the result is the same.

**Comment by xhdix** [comment] 2021-10-29 21:36
there is still same problem on Android for TV:

![image](https://user-images.githubusercontent.com/12384263/139460446-69961f67-095d-412d-8a6e-4b8ddf5a42f0.png)

![image](https://user-images.githubusercontent.com/12384263/139460498-196acc87-1747-4b45-bb9d-ae9488d9e4cd.png)

Is MOAT error here related to this issue?
![image](https://user-images.githubusercontent.com/12384263/139504274-dbf9235b-09b4-4256-b5bb-b9e955e1246e.png)

**Comment by syphyr** [comment] 2021-10-29 23:02
Is this only happening when orbot's VPN mode is enabled?

**Comment by xhdix** [comment] 2021-10-29 23:20
@syphyr : for me? If I enable VPN mode on TV, it will crash.

**Comment by jhoc2000** [comment] 2022-01-03 03:26
I'm getting the same problem with VPN enabled but it gets to 95% bootstrapped and then stops.

If I switch off VPN mode then Orbot will get to 100% bootstrapped but then when I switch on VPN mode, the Orbot app stops.

I also noticed that if I do get Orbot to work, I have to regularly stop Orbot and then start it again for other apps to get access to the onion ring.

I'm running:

Version 16.4.1-RC-2-tor.0.4.4.6

On  Xiaomi Pocophone F1

With lineage_beryllium-userdebug 11 RQ3A.211001.001 10037898 (Android 11)

Without any Gapps of any kind.

**Comment by jhoc2000** [comment] 2022-01-03 03:29
I just got Orbot to 100% but then got this error in the log:

NOTICE: Bootstrapped 100% (done): Done 
NOTICE: Guard ibksturm01 ($EB0DB065BFB5F4FF04AAACABD287C7196FF700DC) is failing to carry more streams on its circuits than usual. Most likely this means the Tor network is overloaded or your network connection is poor. Use counts are 46/72. Success counts are 200/236. 226 circuits completed, 9 were unusable, 18 collapsed, and 294 timed out. For reference, your timeout cutoff is 60 seconds.

**Comment by xhdix** [comment] 2022-01-03 17:07
@jhoc2000 I had same issue yesterday in `Tor 0.4.6.7 running on Linux`:

 `Guard bauruine ($CE55315C000D3C8713A4E4B4FE0144371DC84A40) is failing an extremely large amoun...` 
 
My workaround was to stop the service and start again.

If you still can reproduce it, maybe you should open a new issue here: https://gitlab.torproject.org/

**Comment by n8fr8** [comment] 2022-01-03 19:17
This does seem like an issue with the tor network itself... that said, we've just posted a new release candidate of Orbot for testing: https://github.com/guardianproject/orbot/releases/tag/16.5.2-RC-5-tor.0.4.6.9

**Comment by xhdix** [comment] 2022-01-04 10:25
Looks good and works fine for me.

![image](https://user-images.githubusercontent.com/12384263/148043195-ba05c9c4-ee96-4d95-a191-9f46a50b1c61.png)

Over the years, one thing I often hear about normal Orbot usage is high battery consumption. I think this should be optimized as much as possible. Also, do not the snowflakes in this image increase battery consumption? It's nice, but it urges me not to enable proxy mode.

(Also now Snowflake proxy data usage is on foreground not background! :thinking: )

**Comment by n8fr8** [comment] 2022-01-04 16:32
Currently, if you aren't using Orbot, meaning no apps are routing traffic through it either directly via proxy or through the VPN, then the tor daemon will go to sleep entirely and not consume any battery. The idea that Orbot has "high battery consumption" is actually a bit misleading, in that all of the battery drain associated with network traffic for any app going through Tor is assigned to Orbot, and not just generated by the tor daemon itself.

The snowflake in the image only use battery when the Orbot window is visible, and not when the app is in the background. We are working on a more formal and professional display of the entire Snowflake proxy mode feature, which will be out in the next major release.

>(Also now Snowflake proxy data usage is on foreground not background! 🤔 )

Can you explain what you mean a bit more?

**Comment by xhdix** [comment] 2022-01-04 18:43
>  The idea that Orbot has "high battery consumption" is actually a bit misleading, in that all of the battery drain associated with network traffic for any app going through Tor is assigned to Orbot, and not just generated by the tor daemon itself.

Yes. sorry. I think it is related to how Tor itself is working. It do a lot more than any other VPN/Proxies.

> Can you explain what you mean a bit more?

Sorry, This seems to be related to the Android version.

Android 6 (a month ago) :

![image](https://user-images.githubusercontent.com/12384263/148094885-c2c4cc4b-620d-4544-b0b8-7d1d3b8d2254.png)

Android 9 (now):

![image](https://user-images.githubusercontent.com/12384263/148095046-63f058a6-17cd-4e44-8229-165257c3603e.png)

(I'm testing the new version on Android 6 now and still is the same as before.)

**Comment by n8fr8** [comment] 2022-01-04 19:46
Interesting. Well, Tor does run as part of the Orbot Service which is a "Foreground Service". We have also switched to running Tor as a separate daemon/process to having it run in-process through a new tor-android shared library. That may have to do with how the traffic is categorized as foreground now, as well.

**Comment by bitmold** [comment] 2022-07-29 19:21
Closing this since the issue is resolved but will look into the MOAT flows

**Closed** 2022-07-29 19:22 UTC

**Comment by 62sss82** [comment] 2022-07-30 14:55
![Screenshot_2022-07-30-19-49-42-460_org torproject android](https://user-images.githubusercontent.com/110296727/181919917-25f0c216-b623-42e8-8700-6ff0d1891016.jpg)
![Screenshot_2022-07-30-19-42-05-086_org torproject android](https://user-images.githubusercontent.com/110296727/181919920-24ff60ce-80f2-45bc-a92c-aed862a20281.jpg)
Help please😕😰

**Comment by 62sss82** [comment] 2022-07-30 14:56
![Screenshot_2022-07-30-19-42-05-086_org torproject android](https://user-images.githubusercontent.com/110296727/181919959-d0fc6af8-3b3e-458f-b073-3b1b27a4fdfc.jpg)
Help please😰😕

**Comment by 62sss82** [comment] 2022-07-30 14:58
![Screenshot_2022-07-30-19-42-05-086_org torproject android](https://user-images.githubusercontent.com/110296727/181920042-ffa65201-5eb4-42d6-bfb1-4acaa38e08ca.jpg)
![IMG_20220730_195735](https://user-images.githubusercontent.com/110296727/181920044-a08cb8b6-e46c-4e0b-8986-cc334cba164b.jpg)
Help,please😕😰

**Comment by bitmold** [comment] 2022-07-30 15:25
Does your issue persist when using the latest Orbot? 
https://github.com/guardianproject/orbot/releases/tag/16.6.2-RC-4-tor.0.4.7.8.1

**Comment by 62sss82** [comment] 2022-07-30 18:11
> Проблема сохраняется при использовании последней версии Orbot? https://github.com/guardianproject/orbot/releases/tag/16.6.2-RC-4-tor.0.4.7.8.1

No all versions ,what can I do? In my country every vpn blocked😕

**Comment by 62sss82** [comment] 2022-07-30 18:12
> Проблема сбора последней версии Orbot? https://github.com/guardianproject/orbot/releases/tag/16.6.2-RC-4-tor.0.4.7.8.1

Do you know Turkmenistan?

**Comment by 62sss82** [comment] 2022-07-30 18:16
> Проблема сохраняется при использовании последней версии Orbot? https://github.com/guardianproject/orbot/releases/tag/16.6.2-RC-4-tor.0.4.7.8.1

Used to work well but this month it stopped working

**Comment by syphyr** [comment] 2022-07-30 18:29
> > Проблема сохраняется при использовании последней версии Orbot? https://github.com/guardianproject/orbot/releases/tag/16.6.2-RC-4-tor.0.4.7.8.1
> 
> Used to work well but this month it stopped working

Maybe you need to use a bridge now.

**Comment by 62sss82** [comment] 2022-07-30 18:34
> > > Проблема сбора последней версии Orbot? https://github.com/guardianproject/orbot/releases/tag/16.6.2-RC-4-tor.0.4.7.8.1
> > 
> > 
> > Раньше работало хорошо, но в этом месяце перестало работать
> 
> Может быть, вам нужно использовать мост сейчас.

No, bridges don't work either.

**Comment by 62sss82** [comment] 2022-07-30 18:37
![Uploading Screenshot_2022-07-30-23-35-48-864_org.torproject.android.jpg…]()

**Comment by 62sss82** [comment] 2022-07-30 18:43
> > > Проблема сбора последней версии Orbot? https://github.com/guardianproject/orbot/releases/tag/16.6.2-RC-4-tor.0.4.7.8.1
> > 
> > 
> > Раньше работало хорошо, но в этом месяце перестало работать
> 
> Может быть, вам нужно использовать мост сейчас.

1 vpn we will find and in our country in a few days they block
