### ISSUE TITLE
Feature Request: Add 'client authorization' option for v3 onion service.

### ISSUE THREAD

**Issue by n1m1** [guardianproject/orbot#265] opened 2019-10-06 11:05 UTC
As per title. 

The current version of Orbot has already implemented such option (under` Onion Services -> Client Cookies`) but only for v2 onion services.

Client authorization for v3 onion services has been introduced in [Tor 0.3.5.7](https://blog.torproject.org/new-releases-tor-0357-03410-and-03311). 

The issue is being discussed here #216 (with some possible workarounds suggested). However the title of the issue was not specific enough, so I have opened a new one.

**Comment by ScriptTiger** [comment] 2020-01-29 02:23
> Feature Request: Add 'client authorization' option for v3 **`stealth`** onion service.

I obviously agree with the need for v3 client authorization, so in total support of this issue, since v3 services requiring such are currently completely inaccessible. However, I would just say maybe the word "stealth" should be removed from the issue title to eliminate any possible confusion, as there is no such thing as v3 stealth at this time and it could be misunderstood as a request to implement a nonexistent feature.

**Comment by n1m1** [comment] 2020-03-26 09:18
Yeah, right. Done.

**Comment by n1m1** [comment] 2020-06-17 09:29
About this issue. A couple of days ago, on the tor-dev ml the [Onion Service V2 deprecation deadline](https://lists.torproject.org/pipermail/tor-dev/2020-June/014365.html) has been published.

> The deprecation to obsolescence timeline:
> 
>   1) September 15th, 2020
>      0.4.4.x: Tor will start warning onion service operators and clients that
>               v2 is deprecated and will be obsolete in version 0.4.6
> 
>   2) July 15th, 2021
>      0.4.6.x: Tor will no longer support v2 and will be removed from the code
>               base.
> 
>   3) October 15th, 2021
>      We will release new stable versions for all supported series that will
>      disable v2

Cheers.

**Comment by fabacab** [comment] 2020-08-12 23:04
Just chiming in to let you know that the lack of Tor client authentication for V3 Onion services in Orbot has been a blocker for several projects I'm involved in. The issue is that while our affected infrastructures are ready to move to V3 Onion services, few of our Android users will be able to connect once we retire the V2 stealth services, because these users won't be able to connect with Orbot like they do now. We're hoping this can be resolved soon enough to avoid a major disruption for our mobile user base.

Thanks!

**Comment by ScriptTiger** [comment] 2020-08-13 04:17
@n8fr8, shouldn't this issue be promoted to a higher priority and pulled into the current sprint?

I know that time and other resources are tight for the devs, and we all really appreciate the effort that goes into this, obviously, as we are all obviously fans and are concerned deeply with the future of this app, which is why we take the time to engage here. But it seems like this issue directly relates to a core functionality of Orbot, unlike a bulk of the other issues currently categorized into the current and next sprint. Being worried about performance or intermittent app crashing are simply nonissues when compared to the guarantee that next year this app will simply not work at all for some people, guaranteed. Waiting until the last second to address it is putting both the devs and the user base at risk, not to mention also making a great deal of people feel uneasy unnecessarily.

I know everything must come in due time and we of course must adhere to a system and keep order with how we prioritize things in the dev cycle, but I am just saying I think this should be looked at again in terms of priority and urgency. Not all critical issues are nice enough to give us an exact deadline, but the Tor Project has done just that in this case. I just think we should take advantage of that when we can.

**Comment by bitmold** [comment] 2020-11-29 19:25
I recently made a pull request to add V3 onion services to Orbot, although it does not yet support client authorization which we realize is a significant feature for many people developing secure software. The next thing I plan on working on is incorporating an ed25519 library to allow Orbot users to manage authorization for their services

**Comment by n1m1** [comment] 2020-11-29 21:51
> I recently made a pull request to add V3 onion services to Orbot, although it does not yet support client authorization which we realize is a significant feature for many people developing secure software. 

May The God bless you for this.

>The next thing I plan on working on is incorporating an ed25519 library to allow Orbot users to manage authorization for their services

Fantastic. When there is a beta I will be glad to test it. Even an alpha. Even a few lines of crappy code pushed in an apk not properly signed.

Cheers.

P.s: for the record: this feature is not only relevant for people developing software but also for random users like me (I use v3 client authorization to make my own and self-managed Nextcloud instance more secure).

**Comment by bitmold** [comment] 2021-01-28 21:12
@n1m1  if you want to test this fork this growing PR supports v3 client authorization now

**Comment by n1m1** [comment] 2021-01-28 21:42
This is fantastic! Yes, I am more than happy to test. Is there an APK that I can use?

**Comment by bitmold** [comment] 2021-01-28 22:28
ahh I don't think the CI thing is working for me.. so no...., I can build one the next time I'm on my computer (~24hrs)

**Comment by n1m1** [comment] 2021-02-13 12:09
Hi @bitmold ! No apk for testing this new feature?

**Comment by bitmold** [comment] 2021-02-23 04:25
Here https://github.com/guardianproject/orbot/releases/tag/16.4.1-BETA-2-tor.0.4.4.6

**Comment by n1m1** [comment] 2021-02-23 18:18
Fantastic!

Two problems I have noticed:

1) I have manually set up a v3 onion client authorization. The manual set up works and I can connect my onion service. I have tested the connection with DAVx5. 

Unfortunately, in order to do a more extensive test I'd need #441 to be fixed (or a way to workaround it). Indeed, I cannot use the Android Nextcloud client with Orbot without using the VPN mode, since, for some reasons, it does not support local proxy (more here https://github.com/nextcloud/android/issues/606).

2) I have tried to import a foobar.auth_private with Orbot, but I cannot select it. Yet if I rename it from "foobar.auth_private" to "foobar.auth_private.txt" I can import the client authorization key.

**Comment by n8fr8** [comment] 2021-02-23 18:41
For now, you can just use the VPN without selecting any apps, and it will route all the traffic through Tor.

**Comment by n8fr8** [comment] 2021-02-23 18:42
You can also try the WebDAV app we built called Save. It has built in Orbot support. It is meant for one-way archiving/upload but should be enough for testing.

https://open-archive.org/

https://play.google.com/store/apps/details?id=net.opendasharchive.openarchive.release&hl=en

https://github.com/OpenArchive/Save-app-android/releases/tag/0.2.3-RC-1

**Comment by n1m1** [comment] 2021-02-23 20:08
> For now, you can just use the VPN without selecting any apps, and it will route all the traffic through Tor.

Hi!
Yes of course. I just tested it and I can connect to my Nextcloud instance. It works.

However, routing all my traffic through Orbot is not an optimal setup for my needs. In order  to test a daily use of Orbot client authorization with my Nextcloud instance I will need to route it in VPN mode.

Cheers.

**Comment by bitmold** [comment] 2021-03-01 20:58
> I have tried to import a foobar.auth_private with Orbot, but I cannot select it. Yet if I rename it from "foobar.auth_private" to "foobar.auth_private.txt" I can import the client authorization key.

Thanks for this feedback, I just made #442 which addresses this point. I'm glad everything else seems to be working & getting resolved.

If there are no other issues after $442 gets merged I think we can finally close this ticket?!

**Comment by ScriptTiger** [comment] 2021-03-01 21:47
I would first like to thank @n1m1 for really going above and beyond and starting this issue in order to properly categorize and label the issue at hand, as well as really staying on top of it and seeing it to the end.

And then last but certainly not least, I'd also like to thank @bitmold for obviously making this happen and making the necessary material changes to bring about truly positive, transformational, impactful change here.

**Comment by n1m1** [comment] 2021-03-02 10:41
> I would first like to thank @n1m1 for really going above and beyond and starting this issue in order to properly categorize and label the issue at hand, as well as really staying on top of it and seeing it to the end.

Hi, thanks for this, but I haven't done nothing of relevant... Actually I haven't done nothing! :-D @bitmold did all the work!


> Thanks for this feedback, I just made #442 which addresses this point. I'm glad everything else seems to be working & getting resolved.
> 
> If there are no other issues after $442 gets merged I think we can finally close this ticket?!

I haven't found any other issues. I have been testing Orbot with my self-managed Nextcloud instance for one week. Uploading photos and files, using Dav5X for contacts and calendars, backing up my smartphone with Seedvault: everything worked as expected. So, yes, when you think it is suitable, tell me and I will close this ticket.

**Closed** 2022-02-17 21:39 UTC
Labels: enhancement, v3 onion services
