### ISSUE TITLE
Orbot stuck while starting

### ISSUE THREAD

**Issue by anwar-alsilwy** [guardianproject/orbot#656] opened 2022-04-07 20:37 UTC
Hi ...
I noticed that when orbot starting, It just says (Connected to the Tor) immediately, But in the Log, the bootstrapped stuck at 5%  see below:

![tempFile_2022-04-07-23-02-12](https://user-images.githubusercontent.com/71539261/162290099-1efd520a-5e3f-4605-aa9e-c3c64700bb70.jpg)

and the download/upload speed stuck at 0d/0u too, see below:

![tempFile_2022-04-07-23-20-05](https://user-images.githubusercontent.com/71539261/162290223-e7a014f6-8ad8-445e-b382-be60282c8dd2.jpg)

Although the tor is connected, Notification also stuck at ( orbot is starting progress), without showing IP address or exit country, see below:

![tempFile_2022-04-07-23-11-24](https://user-images.githubusercontent.com/71539261/162290346-06195779-7de6-422c-bcd3-cbcd9f73e6b1.jpg)

This issue not fixed until the latest release !!!
I'm using: Orbot-16.6.1-RC-1-tor.0.4.6.10
Android: 5.0 Armv7a.

I hope this issue fixed soon,
Thank you so much for your efforts.

**Comment by bitmold** [comment] 2022-04-12 19:56
Closing this because it's a duplicate of #621 which I'm actively working on..

**Closed by bitmold** 2022-04-12 19:56 UTC
