### ISSUE TITLE
Last version working on Lineageos 14.1 is 16.1.1-BETA-2-tor-0.4.0.4-rc (F-Droid Guardian archive repo)

### ISSUE THREAD

**Issue by tlaurion** [guardianproject/orbot#308] opened 2020-03-08 19:05 UTC
Last version is not useable:
- Open SOCKS5 prior of establishing circuits: (#306) 
- Stalls on automatic startup and manual startup (can open other ticket, but its documented on forums. Suggestion is to wipe cache and restart. Works but is not viable since #306)

Last functional version is : [Lineageos 14.1 is 16.1.1-BETA-2-tor-0.4.0.4-rc](https://forum.f-droid.org/t/orbot-incompatible-only-versions-are-uploaded-to-f-droid-lineageos-14-1-not-supported-anymore/8079/4)

**Comment by n8fr8** [comment] 2020-03-09 16:17
You cannot use a more recent version of Lineage?

This release was tested extensively on Lineage 16:
https://github.com/guardianproject/orbot/releases/tag/16.1.4-RC-1-tor-0.4.2.5-rc

**Comment by tlaurion** [comment] 2020-03-09 16:54
@n8fr8 : nope. N7105, N7000, i9305, i9300 and other Replicant supported phones ([Replicant 9 work ongoing](https://redmine.replicant.us/projects/replicant/wiki/PortingToAndroid9#LineageOS-16)) is not supporting LineageOS 14+ as we speak.

Solution would then be to not propose anything else then Lineageos 14.1 is 16.1.1-BETA-2-tor-0.4.0.4-rc for LineageOS 14.1 based devices or try to make it work for those devices. Else security is broken for those users seeking more security and privacy.

[Open source enforced devices](https://redmine.replicant.us/projects/replicant/wiki/PortingToAndroid9#Devices-support)
[Work needing to be done prior of LineageOS accepting those devices in more recent LineageOS automatic builds]([Ongoing work](https://github.com/CustomROMs/android_local_manifests_i9300/issues/1))

e.foundation builds: 
- [N7100](https://images.ecloud.global/dev/n7100/)
- [N7105](https://images.ecloud.global/dev/n7105/)
- [I9305](https://images.ecloud.global/dev/i9305/)

**Comment by herbsmn** [comment] 2020-04-09 22:52
@n8fr8 i work with Replicant. if you'd like one of our supported devices in order to do testing on it, let me know and i can try to get you one.

**Comment by jhoc2000** [comment] 2020-04-14 02:45
It's the same problem with LineageOS 17.1-20200405-NIGHTLY-beryllium. Orbot hands Pb starting. Eg.

"checking binary version: 0.4.2.5-openssl1.0.2p
upgrading binaries to latest version: 0.4.2.5-openssl1.0.2p
Waiting for control port...
checking binary version: 0.4.2.5-openssl1.0.2p
updating settings in Tor service
updating torrc custom configuration...
success."

It doesn't get to building a circuit.

**Comment by n8fr8** [comment] 2020-04-26 12:57
We've made a few updates in the next release that may resolve this. Will be testing specifically on Lineage.

**Comment by herbsmn** [comment] 2020-04-27 16:42
Thank you @n8fr8. I look forward to testing it.

**Comment by herbsmn** [comment] 2020-04-30 21:18
I tested this version of Orbot on my N7100 with Replicant and everything seems to be working properly: https://github.com/guardianproject/orbot/releases/tag/16.2.0-BETA-1-tor-0.4.2.7

If @tlaurion feels the same, please feel free to close this ticket.

Thanks for all the work you all are doing!

**Comment by herbsmn** [comment] 2020-04-30 22:55
I'm really hoping that whatever was fixed in Orbot's latest release so that it now works in Replicant will also fix this issue in Tor Browser on Replicant as well: https://trac.torproject.org/projects/tor/ticket/32723

**Comment by tlaurion** [comment] 2020-05-01 01:20
Reliable again. Thanks!

On April 30, 2020 9:18:50 PM UTC, "FreeKurt.com" <notifications@github.com> wrote:
>I tested this version of Orbot on my N7100 with Replicant and
>everything seems to be working properly:
>https://github.com/guardianproject/orbot/releases/tag/16.2.0-BETA-1-tor-0.4.2.7
>
>If @tlaurion feels the same, please feel free to close this ticket.
>
>Thanks for all the work you all are doing!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/guardianproject/orbot/issues/308#issuecomment-622119063

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jhoc2000** [comment] 2020-05-01 01:38
That version is not yet available on F-Droid. When can we expect it to be available for testing?

**Comment by n8fr8** [comment] 2020-05-01 04:20
@herbsmn I hope so, as they do utilize our same core tor binary releases.

Beta 2 is out now: New build for testing: https://github.com/guardianproject/orbot/releases/tag/16.2.0-BETA-2-tor-0.4.2.7

@jhoc2000 once we can do a bit more wider testing in the next few days, then I will feel comfortable pushing to F-Droid. This was a pretty big update, and we need to make sure our new beta code is stable and ready.

**Comment by n8fr8** [comment] 2020-05-01 18:06
Please test: https://github.com/guardianproject/orbot/releases/tag/16.2.0-BETA-3-tor-0.4.2.7
with a fresh install. Thanks!

**Comment by herbsmn** [comment] 2020-05-02 00:18
> Please test: https://github.com/guardianproject/orbot/releases/tag/16.2.0-BETA-3-tor-0.4.2.7
> with a fresh install. Thanks!

Working great! Thanks so much for your excellent work on this and for following up with me.

Please feel free to reach out when you have a next Tor Browser pre-release if you'd like me to test whether that too is now working in Replicant.

**Comment by jhoc2000** [comment] 2020-05-02 00:49
That version isn't yet available via the F-Droid app.

**Comment by tlaurion** [comment] 2020-05-02 00:52
I confirm a really stable outcome on i317 (n7105 can+us) of latest beta

On May 2, 2020 12:18:53 AM UTC, "FreeKurt.com" <notifications@github.com> wrote:
>> Please test:
>https://github.com/guardianproject/orbot/releases/tag/16.2.0-BETA-3-tor-0.4.2.7
>> with a fresh install. Thanks!
>
>Working great! Thanks so much for your excellent work on this and for
>following up with me.
>
>Please feel free to reach out when you have a next Tor Browser
>pre-release if you'd like me to test whether that too is now working in
>Replicant.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/guardianproject/orbot/issues/308#issuecomment-622623061

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tlaurion** [comment] 2020-05-25 03:54
> @herbsmn I hope so, as they do utilize our same core tor binary releases.
> 
> Beta 2 is out now: New build for testing: https://github.com/guardianproject/orbot/releases/tag/16.2.0-BETA-2-tor-0.4.2.7
> 
> @jhoc2000 once we can do a bit more wider testing in the next few days, then I will feel comfortable pushing to F-Droid. This was a pretty big update, and we need to make sure our new beta code is stable and ready.

@n8fr8 : F-droid proposes me to update old update of 3 moths ago on latest deployed beta.
Do you plan on pushing to f-droid soon? This is more stable then old one. Would say, without one, single, usability glitch, on my side.

**Comment by jhoc2000** [comment] 2020-05-25 23:22
Thanks for telling me that. I've been checking F-Droid each day for 16.2..... and wondering why it wasn't available. It's good to know that it will be fully tested before I get to.

**Comment by herbsmn** [comment] 2020-05-26 02:21
>> I'm really hoping that whatever was fixed in Orbot's latest release so that it now works in Replicant will also fix this issue in Tor Browser on Replicant as well: https://trac.torproject.org/projects/tor/ticket/32723

> @herbsmn I hope so, as they do utilize our same core tor binary releases.

I can confirm that Tor Browser Alpha on F-Droid released on May 11th, 2020 works properly on Replicant. I'm pretty sure that versions before that didn't work, but I think they have been removed from F-Droid so I can't 100% confirm that.

**Comment by tlaurion** [comment] 2020-06-03 12:52
I still have some weird issues with latest fdroid orbot, which seems GUI related and not backend related. 

When roaming and changing networks, Orbot shows "Starting Orbot". Applications told to use Netguard to access internet goes through VPN (Netguard) then hits the tor backend and successfully is routed through tor. tor Proxy is up and functioning, as DNS proxy. PrivacyBrowser, used under this use case, hits https://check.torproject.org and tells that it is behind tor correctly.

**Comment by tlaurion** [comment] 2020-06-03 12:54
I would again advise in having Tor Browser and orbot use a different set of ports by default. In my case, I've setuped orbot to be default+1 ports (9501, 4501), so that using Tor Browser can be instructed through Netguard to use Orbot without conflict  (9500, 4500)

**Comment by herbsmn** [comment] 2020-06-18 02:00
> @n8fr8 I still have some weird issues with latest fdroid orbot, which seems GUI related and not backend related.

I can confirm that I'm having the same issues.

**Comment by herbsmn** [comment] 2020-07-24 15:06
I'm available to test out any releases that you might have to see if they fix this bug.

**Closed** 2020-09-08 17:50 UTC
Labels: PLEASE TEST, bug

**Comment by herbsmn** [comment] 2020-09-08 21:54
Thanks for closing this. I can confirm that the bug was fixed in Orbot 16.3.1-BETA-2-tor-0.4.3.6.
