### ISSUE TITLE
Error while running make -C external 

### ISSUE THREAD

**Issue by Joe-Mobarak-WoLf** [guardianproject/orbot#93] opened 2017-11-01 14:13 UTC
make -C external 

test -d lib || mkdir lib
test -d include || mkdir include
test -d include/openssl || mkdir include/openssl
cp openssl/libcrypto.a lib/libcrypto.a
cp openssl/libssl.a lib/libssl.a
cp openssl/include/openssl/* include/openssl
sed -i 's@\(SUBDIRS = . include\) sample test@\1@' libevent/Makefile.am
sed: 1: "libevent/Makefile.am": extra characters at the end of l command
make: *** [libevent/Makefile] Error 1

Note : I have downloaded autoconf automake and libtool and using ndk r10e
Some help would be nice

**Comment by danyhaddad** [comment] 2017-11-03 08:21
I am facing the same problem, any help guys ?

**Comment by goapunk** [comment] 2017-11-08 09:41
You could try adding '' (two single quotes) after the -i in line 164 so it looks like this:
```
sed -i '' 's@(SUBDIRS = . include) sample test@\1@' libevent/Makefile.am
```

**Comment by dovanvu1792** [comment] 2018-02-10 16:31
What does "make -C external" do?
I downloaded and ran Tor project use android studio. But When i active some app like firefox or chorme to use Tor via VPN mode. Only show Sorry You are not using Tor. also Orfox normal working (Congratulations. This browser is configred to use Tor). I tried build debug and sign new apk, but it not working. Anybody can help me to fix it. 
Version name: 16.0.0-RC-2-multi-SDK16
versionCode 16000010
Have some Logs:
=======================
Log 1: 
=======================
02-09 11:31:45.934 2450-7273/org.torproject.android1 D/OrbotVpnService: tun2Socks has stopped
java.io.IOException: Error running exec(). Command: -c, /data/data/org.torproject.android1/app_bin/pdnsd.conf Working Directory: null Environment: [ANDROID_ROOT=/system, EMULATED_STORAGE_SOURCE=/mnt/shell/emulated, LOOP_MOUNTPOINT=/mnt/obb, LD_PRELOAD=libsigchain.so:libNimsWrap.so, ANDROID_BOOTLOGO=1, EMULATED_STORAGE_TARGET=/storage/emulated, EXTERNAL_STORAGE=/storage/emulated/legacy, SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar, ANDROID_SOCKET_zygote=9, PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin, ANDROID_DATA=/data, ANDROID_ASSETS=/system/app, ASEC_MOUNTPOINT=/mnt/asec, BOOTCLASSPATH=/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/mms-common.jar:/system/framework/android.policy.jar:/system/framework/apache-xml.jar:/system/framework/qcmediaplayer.jar:/system/framework/org.codeaurora.Performance.jar:/system/framework/vcard.jar:/system/framework/tcmiface.jar:/system/framework/qcom.fmradio.jar:/system/framework/oem-services.jar, ANDROID_PROPERTY_WORKSPACE=8,0, SECONDARY_STORAGE=/storage/sdcard1, ANDROID_STORAGE=/storage]
at java.lang.ProcessManager.exec(ProcessManager.java:211)
at java.lang.ProcessBuilder.start(ProcessBuilder.java:195)
at org.torproject.android.service.vpn.OrbotVpnManager.startDNS(OrbotVpnManager.java:413)
at org.torproject.android.service.vpn.OrbotVpnManager.access$400(OrbotVpnManager.java:55)
at org.torproject.android.service.vpn.OrbotVpnManager$2.run(OrbotVpnManager.java:295)
Caused by: java.io.IOException: No such file or directory
at java.lang.ProcessManager.exec(Native Method)
at java.lang.ProcessManager.exec(ProcessManager.java:209)
at java.lang.ProcessBuilder.start(ProcessBuilder.java:195) 
at org.torproject.android.service.vpn.OrbotVpnManager.startDNS(OrbotVpnManager.java:413) 
at org.torproject.android.service.vpn.OrbotVpnManager.access$400(OrbotVpnManager.java:55) 
at org.torproject.android.service.vpn.OrbotVpnManager$2.run(OrbotVpnManager.java:295) 
=======================
Log 2: 
=======================
02-09 11:34:17.449 8881-8985/org.torproject.android E/Orbot: error onBind
java.io.FileNotFoundException: armeabi/obfs4proxy.mp3
at android.content.res.AssetManager.openAsset(Native Method)
at android.content.res.AssetManager.open(AssetManager.java:318)
at android.content.res.AssetManager.open(AssetManager.java:292)
at org.torproject.android.service.util.OtherResourceInstaller.installResources(OtherResourceInstaller.java:77)
at org.torproject.android.service.TorService.torUpgradeAndConfig(TorService.java:650)
at org.torproject.android.service.TorService.access$800(TorService.java:90)
at org.torproject.android.service.TorService$2.run(TorService.java:599)
at java.lang.Thread.run(Thread.java:818)

**Comment by dovanvu1792** [comment] 2018-02-10 17:00
I did, but have some errors logcat :((

Orbot includes, in the external directory, git repo submodules of:
	- JTorControl: The Tor Control Library for Java
How do i do with this?

**Comment by goapunk** [comment] 2018-02-10 17:04
That's just an info, you don't have to do anything. 
Executing the following steps should be sufficient:
```
git submodule update --init --recursive
cd orbotservice/src/main && ndk-build
android update project --name Orbot --target android-15 --path .
```
Now build the apk with Android Studio.

**Comment by dovanvu1792** [comment] 2018-02-10 17:21
It does not working with Chrome or firefox, only working with Orfox browser. It is crazy!

**Comment by dovanvu1792** [comment] 2018-02-11 03:51
@goapunk  Is your build working with another app like chrome or firefox?

**Comment by goapunk** [comment] 2018-02-11 15:20
@dovanvu1792 
Ok, I can confirm it's a bug. You can workaround it until it's fixed like this:
```
cd orbotservice/src/main/
mkdir -p assets/armeabi
</path/to/ndk>/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip libs/armeabi/pdnsd 
zip assets/armeabi/pdnsd.mp3 libs/armeabi/pdnsd
```
now build the apk and it should work.

**Comment by dovanvu1792** [comment] 2018-02-11 16:08
It not working!
as logcat show
02-09 11:34:17.449 8881-8985/org.torproject.android E/Orbot: error onBind
java.io.FileNotFoundException: armeabi/obfs4proxy.mp3
at android.content.res.AssetManager.openAsset(Native Method)
at android.content.res.AssetManager.open(AssetManager.java:318)
at android.content.res.AssetManager.open(AssetManager.java:292)

So, obfs4proxy.mp3 is file not exits not pdnsd.mp3, I tried

**Comment by goapunk** [comment] 2018-02-11 16:43
Ah, sorry, I forgot I commented obfs4proxy out in my build. You need to build pluto as well:

See the instructions in external/pluto/BUILD.md. 
Once you built pluto you can do the following again (inside external/pluto):
```
<path/to/android/ndk/>toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip** bin/android_arm/obfs4proxy
zip ../../orbotservice/src/main/assets/armeabi/obfs4proxy.mp3 bin/android_arm/obfs4proxy 
```

**Comment by dovanvu1792** [comment] 2018-02-13 15:50
Thank man! It is working 
But I want connect to some API in my app use VPN mode, can i do it? Example, Google analytic only show my country =)) I want to Google analytic show location like VPN mode choose.
Now, only webview working with VPN mode.

**Comment by EpicGamer1YT** [comment] 2019-04-09 23:53
Hello, I don't know how to setup the environment to build pluto... How do I do this?

**Comment by EpicGamer1YT** [comment] 2019-04-09 23:56
Also, If I don;t need to take this step, the app launches just fine, but then on clicking the button, it is stuck on the starting menu(Orbot is starting...)

**Comment by bitmold** [comment] 2020-11-29 20:08
Closing this because the issues encountered here pertain to an outdated build process for Orbot. If anyone has any problems building Orbot please let me know or write here

**Closed by bitmold** 2020-11-29 20:08 UTC
