### ISSUE TITLE
E/TorNativeLoader: Unable to find file in apk:lib/armeabi-v7a/obfs4proxy

### ISSUE THREAD

**Issue by GentleNi** [guardianproject/orbot#156] opened 2018-05-17 04:57 UTC
when I  run orbot on Android studio using private bridge I got this

**E/TorNativeLoader: Unable to find file in apk:lib/armeabi-v7a/obfs4proxy**

And Logs here
![819719074633460243](https://user-images.githubusercontent.com/8778040/40175884-30ccc196-5a0c-11e8-949c-82e0e8f03209.jpg)

**Comment by lshcoco** [comment] 2018-05-17 11:40
I have got the same error and looking forward to your reply！

**Comment by n8fr8** [comment] 2018-05-18 11:37
Did you install via F-Droid, Google Play, or direct download?

**Comment by gentleni** [comment] 2018-05-18 15:31
I want to add some functionality so I need to compile it myself。
I build orbot follow your BUILD file but got this error.
My Build Info :
Ubuntu 16.04 , Phone Android 7.1, NDK 10

**Comment by bitmold** [comment] 2018-08-02 18:07
Were you able to run `ndk-build` from the `orbotservice/src/main` directory? Building the app through Android Studio is insufficient to get the native components to build.

**Comment by bitmold** [comment] 2020-11-29 19:49
Closing because this is dated and not something I can reproduce. If anyone is still having problems with building Orbot and/or getting obfs4 to work with it please let me know

**Closed by bitmold** 2020-11-29 19:49 UTC
